### ISSUE TITLE
How to start a Program from VsCode?

### ISSUE THREAD

**Issue by Rasenkantenstein** [samaguire/TabularEditorScripts#30]
Hi Sam,

due to me being new to C# I was wondering how to start a script for testing from VsCode.

I read that entering the debugging code should work. However, in the launch.json file there's a reference to a dll that doesn't exist in the repo:
![image](https://user-images.githubusercontent.com/6643712/180435185-377aecf4-caf2-42bf-8613-d2f988bde186.png)

Otherwise thank you so much from the abundance of cool csx-files :-)

Konstantin

**Comment by samaguire** [comment]
The scripts are designed to be run from within TE3. There are some references that must be interpreted within the TE3 environment for the scripts to run. i.e. which columns are selected in the GUI.

However, for the purposes of building scripts within VSCode, I've referenced the TE3 assemblies from the default 64bit install directory.

I have in the works importing the scripts/macros into TE3. This when it's done will be one of the few scripts that could be run from outside of TE3.

**Comment by samaguire** [comment]
The recent updates to the report now address this. Please check out the updated ReadMe.
